board/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from board import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^delete/(?P<id_post>\d+)/$', views.delete_post, name='Delete file'),
    url(r'^writeAnswer/(?P<id_post>\d+)/$', views.answer, name='Answer'),
    url(r'^writeComment/(?P<id_post>\d+)/$', views.comment, name='Comment'),
    url(r'^writeComment/(?P<id_post>\d+)/$', views.comment, name='Comment'),
]

esqwiki/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from loginRegistration import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),

    url(r'^login/$', views.Login, name='Login'),
    url(r'^registration/$', views.Register, name='Register'),
    url(r'^logout/$', views.Logout, name='Logout'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    url(r'^$', include("main.urls"), ),
    url(r'^main/', include("main.urls"), name='main'),
    url(r'^board/', include("board.urls"), name='board'),
    url(r'^wiki/', include("wiki.urls"), name='wiki'),
    url(r'^auction/', include("auction.urls"), name='auction'),
    url(r'^trade/', include("trade.urls"), name='trade'),
    url(r'^forum/', include("forum.urls"), name='forum'),
    url(r'^map/', include("worldmap.urls"), name='worldmap'),
    url(r'^detail/', include('userGuildDetail.urls', namespace="userGuildDetail")),
    url(r'^questions/', include('questions.urls', namespace="questions")),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from main import views

urlpatterns = [
    url('', views.index),
]

questions/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from questions import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'rightAnswer/$', views.right_answer, name="right_answer"),
]

userGuildDetail/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from userGuildDetail import views

urlpatterns = [
    url(r'^user/(?P<id_user>\d+)/$', views.user_detail, name='user_detail'),
    url(r'^guild/(?P<id_guild>\d+)/$', views.guild_detail, name='guild_detail'),

]

board/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


class posts(models.Model):
    id_board_post = models.AutoField(primary_key =True)
    id_board_post_parent = models.IntegerField(blank=True, null=True)
    text = models.CharField(max_length=2048)
    deleted = models.BooleanField(default=0)
    x_created = models.DateTimeField(auto_now_add=True)
    x_modified = models.DateTimeField(auto_now=True)
    x_user = models.ForeignKey(settings.AUTH_USER_MODEL)

board/forms.py
from django import forms


class BuySellPost(forms.Form):
    text = forms.CharField(required=True, label="", widget=forms.Textarea(attrs={'rows': 2, 'cols': 50}))

board/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect
from board.models import posts
from questions.views import index as questions_form
from questions.forms import QuestionsNewPost
from questions.models import questions
from forms import BuySellPost


def index(request):
    if request.method == 'POST':
        buy_sell_form_post = BuySellPost(request.POST)
        if buy_sell_form_post.is_valid() and request.POST.get('buySell'):
            text = buy_sell_form_post.cleaned_data.get("text")
            if text:
                record = posts(text=text, x_user_id=request.user.id)
                record.save()

        # call old structure of questions
        if request.POST.get('question'):
            questions_form(request)

    buy_sell_new_post = BuySellPost()
    help_new_post = QuestionsNewPost()

    return render(request, 'board_base.html',
                  {
                      'board_records': prepare_data_questions_block(),# data
                      'sellBuy_records': prepare_data_sell_buy_block(),# data
                      'user': request.user,
                      'help_new_post': help_new_post,# form
                      'sell_buy_new_post': buy_sell_new_post # form
                  })


def prepare_data_questions_block():
    question_array = []
    records_questions = questions.objects.filter(deleted=0, id_question_post_parent=None).order_by('-x_created')
    for record in records_questions:
        answer_array = []
        answers = questions.objects.filter(deleted=0, id_question_post_parent=record.id_question_post).order_by(
            'x_created')
        for answer in answers:
            answer_array.append(answer)

        question_array.append([record, answer_array])

    return question_array


def prepare_data_sell_buy_block():
    sell_buy_array = []
    records_posts = posts.objects.filter(deleted=0, id_board_post_parent=None).order_by('-x_created')
    for record in records_posts:
        sell_buy_comments_array = []
        sell_buy = posts.objects.filter(deleted=0, id_board_post_parent=record.id_board_post).order_by('-x_created')
        for item in sell_buy:
            sell_buy_comments_array.append(item)

        sell_buy_array.append([record, sell_buy_comments_array])
    return sell_buy_array


def delete_post(request, id_post):
    if request.method == 'GET':
        t = posts.objects.get(id_board_post=id_post)
        t.deleted = 1
        t.save()
        messages.success(request, 'Smazání proběhlo úspěšně.')
    return redirect('/board/')


def answer(request, id_post):
    if request.method == 'POST':
        text = request.POST['text']
        if text:
            record = posts(text=text, id_board_post_parent=id_post, x_user_id=request.user.id)
            record.save()
    return redirect('/board/')


def comment(request, id_post):
    if request.method == 'POST':
        text = request.POST['text']
        if text:
            record = questions(text=text, id_question_post_parent=id_post, x_user_id=request.user.id)
            record.save()
    return redirect('/board/')

board/templates/block/buySellBlock.html
{% load filters %}

<button class="board_add_new_record_button" onclick="showBuySellBlock()">Form</button>
    <!-- form -->
<div id="buySellBlock" style="display: none">
    <form action="" method="post">
        {% csrf_token %}
        {{ sell_buy_new_post }}
        <input type="submit" value="Submit" name="buySell"/>
    </form>
</div>


{% if not sellBuy_records %}
    <div class="board_content_record width_100p">
        <strong>No recordsxxx</strong>
    </div>
{% else %}
     {% for record in sellBuy_records %}
                <div class="board_content_record" id="{{ record.0.id_board_post }}_board_content_record">
                    <div>
                        <div class="opacity_05 d-inline-block">
                            <span>#{{ record.0.id_board_post }}</span>
                        </div>
                        <div class="opacity_05 float-right d-inline-block">
                            <span>{{ record.0.x_created |date:"G:i j.n.Y" }} </span>
                            <span>
                                <a href=" {% url 'userGuildDetail:user_detail' id_user=record.0.x_user.id %} ">
                                    {{ record.0.x_user.username }}
                                </a>
                            </span>
                        </div>
                    </div>
                    <b>{{ record.0.text }}</b>
                {% if user.id %}
                    <div class="text-right">
                        <a href="#" onclick="prepareCommentForm({{ record.0.id_board_post }})">Odpovedet</a>
                        {% if user.id == record.0.x_user_id %}
                            <a href="/board/delete/{{ record.0.id_board_post }}">Smazat</a>
                        {% endif %}
                        <a HREF="#">Zprava</a>
                    </div>
                {% endif %}

                <!--
                Answer form for question
                -->

                <div id="{{ record.0.id_board_post }}_comment"></div>
                {% if record.1 %}
                    <div class="board_line"></div>
                    <div class="text-center">
                        <span id="{{ record.0.id_board_post}}_showHideButton" onclick="showHideBuySellComment({{ record.0.id_board_post}})">Zobrazit</span>
                    </div>
                    <div id="{{ record.0.id_board_post}}_buySellComment" style="display:None;">
                        {% for answer in record.1 %}
                            <div class="">
                                <div>
                                    <span><b>{{ answer.text }}</b></span>
                                </div>
                                <div class="opacity_05  d-inline-block float-right">
                                    <span class="float-right">{{ answer.x_created |date:"G:i j.n" }}</span>
                                    <span class="float-right"><b>{{ answer.x_user }}</b></span>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                </div>
            {% endfor %}
{% endif %}
 <script>
        function closeCommentForm(id){
            document.getElementById(id + "_comment").innerHTML = "";
        }
        function prepareCommentForm(id){
            closeCommentForm(id);
            var answer = document.getElementById(id + "_comment");

            var form = document.createElement("form");
            var element = document.createElement("input");
            var button = document.createElement("button");
            var cancel = document.createElement("button");

            element.name="text";

            button.setAttribute("type", "submit");
            button.innerHTML = "Odeslat";

            cancel.setAttribute("type", "button");
            cancel.innerHTML = "Storno";
            cancel.setAttribute("onclick", "closeCommentForm("+id+")");

            var z = document.createElement('input'); // is a node
            z.value = jQuery("[name=csrfmiddlewaretoken]").val();
            z.name = "csrfmiddlewaretoken";
            z.setAttribute("type", "hidden");
            form.appendChild(z);

            form.method = "POST";
            form.action = "/board/writeAnswer/"+id+"/";

            form.appendChild(element);
            form.appendChild(button);
            form.appendChild(cancel);

            answer.appendChild(form);
        }

        function showBuySellBlock()
        {
            var x = document.getElementById("buySellBlock");
              if (x.style.display === "none") {
                x.style.display = "block";
              } else {
                x.style.display = "none";
              }
        }

        function showHideBuySellComment(id)
        {
             var x = document.getElementById(id+"_buySellComment");
             var x_button = document.getElementById(id+"_showHideButton");
              if (x.style.display === "none") {
                x.style.display = "block";
                x_button.innerHTML = "Skrýt";
              } else {
                x.style.display = "none";
                x_button.innerHTML = "Zobrazit";
              }
        }


    </script>

board/templates/block/questionBlock.html
<button class="board_add_new_record_button" onclick="showQuestionBlock()">Form</button>
<!-- form -->
<div id="questionBlock" style="display: none">
    <form action="" method="post">
        {% csrf_token %}
        {{ help_new_post }}
        <input type="submit" value="Submit" name="question"/>
    </form>
</div>


{% if not board_records %}
    <div class="board_content_record width_100p">
        <strong>No records</strong>
    </div>
{% else %}
    {% for record in board_records %}
                <div class="board_content_record" id="{{ record.0.id_question_post }}_board_content_record">
                    <div class="opacity_05 d-inline-block">
                        <span>#{{ record.0.id_question_post }}</span>
                    </div>
                    <div class="opacity_05 float-right d-inline-block">
                        <span>{{ record.0.x_created |date:"G:i j.n.Y" }}</span>
                        <span> {{ record.0.x_user.username }}</span>
                    </div>
                    <br>

                    <b>{{ record.0.text }}</b>
                    {% if user.id %}
                        <div class="text-right">
                            <a href="#" onclick="prepareAnswerForm({{ record.0.id_question_post }})">Odpovedet</a>
                            {% if user.id == record.0.x_user_id %}
                                <a href="/board/delete/{{ record.0.id_question_post }}">Smazat</a>
                            {% endif %}
                            <a HREF="#">Zprava</a>
                        </div>
                    {% endif %}

                <!--
                Answer form for question
                -->

                <div id="{{ record.0.id_question_post }}_answer"></div>
                {% if record.1 %}
                    <div class="board_line"></div>
                    {% for answer in record.1 %}
                            <div>
                              {% if user.id == record.1.x_user_id %}
                                <input type="checkbox" id="{{record.0.id_question_post}}"
                                       name="selected_answer" value={{record.0.is_answer}}
                                 class="select_right_answer">
                              {% else %}
                                <span class="padding_left_15"></span>
                              {% endif %}

                                <span><b>{{ answer.text }}</b></span>
                                <div class="opacity_05  d-inline-block float-right">
                                    <span class="float-right">{{ answer.x_user }}</span>
                                    <span class="float-right">{{ answer.x_created |date:"G:i j.n" }}</span>
                                </div>
                            </div>
                    {% endfor %}
                {% endif %}
                </div>
                <strong>
                {% endfor %}

        {% endif %}

<script type="text/javascript">

        $(function () {
            $('.select_right_answer').on('click', function () {
                var answer_id = $(this).attr('value');
         $.ajax({
                type:  "POST",
                dataType: "json",
                async: true,
                url: '{% url 'questions:right_answer' %}',
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    answer_id: answer_id
                },

                success: function (json) {
                    console.log(json.message);
                        location.reload();
                    }
                })
            });
        });

    function closeAnswerForm(id){
        document.getElementById(id + "_answer").innerHTML = "";
    }

    function prepareAnswerForm(id){
        closeAnswerForm(id);
        var answer = document.getElementById(id + "_answer");

        var form = document.createElement("form");
        var element = document.createElement("input");
        var button = document.createElement("button");
        var cancel = document.createElement("button");

        element.name="text";

        button.setAttribute("type", "submit");
        button.innerHTML = "Odeslat";

        cancel.setAttribute("type", "button");
        cancel.innerHTML = "Storno";
        cancel.setAttribute("onclick", "closeAnswerForm("+id+")");

        var z = document.createElement('input'); // is a node
        z.value = jQuery("[name=csrfmiddlewaretoken]").val();
        z.name = "csrfmiddlewaretoken";
        z.setAttribute("type", "hidden");
        form.appendChild(z);

        form.method = "POST";
        form.action = "/board/writeComment/"+id+"/";

        form.appendChild(element);
        form.appendChild(button);
        form.appendChild(cancel);

        answer.appendChild(form);
    }

    function showQuestionBlock()
    {
        var x = document.getElementById("questionBlock");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }

</script>